name: Nuget Published

on:
  push:
    branches:
      - master
#    paths:
#      - 'manifest.json'

jobs:
  Build_and_Release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nuget
        uses: nuget/setup-nuget@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Publish
        run: |
          $json = Get-Content "manifest.json" | ConvertFrom-Json
          $version = $json.version_number
          cd SetInjectionFlag
          ./update.ps1
          dotnet restore SetInjectionFlag.csproj
          dotnet build SetInjectionFlag.csproj --configuration Release
          cd bin/Release
          dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }} --skip-duplicate
          
      - name: Package for ThunderStore
        run: |
          New-Item -Path 'thunderstore' -ItemType Directory
          Copy-Item -Path icon.png -Destination 'thunderstore'
          Copy-Item -Path License.txt -Destination 'thunderstore'
          Copy-Item -Path manifest.json -Destination 'thunderstore'
          Copy-Item -Path README.md -Destination 'thunderstore'
          Copy-Item -Path SetInjectionFlag/bin/Release/net48/SetInjectionFlagPlugin.dll -Destination 'thunderstore'
      
      - uses: GreenTF/upload-thunderstore-package@v2.2
        with:
          namespace: brcoding # the thunderstore 'team' to publish under
          description: Allows players to flag that mods are installed for BouncyRock.
          token: ${{ secrets.BRCODING_TOKEN }}
          name: SetInjectionFlagPlugin # the name of the package
          version: $version # Use the version from manifest
          community: talespire
          path: thunderstore
          wrap: thunderstore
          deps: bbepisTaleSpire-BepInExPack@5.4.10
